### ISSUE TITLE
HTML content is getting changed by editor

### ISSUE THREAD

**Issue by nlonidier-sixmo** [vueup/vueup-quill#397]
**Version**
@vueup/vue-quill version 1.1.1. I upgraded to 1.2.0 to see if that would resolve the issue but it did not.

**Describe the bug**
I've read through the other issues but did not see anyone having this exact issue. 

I am passing a string of HTML content to the QuillEditor component only to have it return a different HTML string, losing a significant portion of my content. This may be something very simple I'm overlooking but I've been struggling to find a suitable solution or work around. 

Here is a preview of my existing component:

<QuillEditor :content="modelValue" @update:content="update($event)" :content-type="html" :toolbar="toolbarOptions" :style="`height: ${height}px;`" />

This is the HTML I am providing via the :content (coming directly from Microsoft Graph API, containing an email message chain). 

```
<p>SaVE 1111</p>
<p><br></p>
<p>sAVE 222222</p>
<hr style="display:inline-block; width:98%" tabindex="-1">
<div id="divRplyFwdMsg" dir="ltr">
<font style="font-size:11pt" face="Calibri, sans-serif" color="#000000">
<b>From:</b> SendersName r &lt;sendersName@email.com&gt;<br>
<b>Sent:</b> Tuesday, July 11, 2023 5:33:53 PM<br>
<b>To:</b> RecipientsName &lt;recipient@email.com&gt;<br>
<b>Subject:</b> Re: Testing</font> 
<div>&nbsp;</div>
</div>
<div><p>Ok. Saving a reply all draft now</p><p><br></p></div>
```

**Expected behavior**
I was expecting to see the HTML rendered in the QuillEditor but the new Value sent back from the @update:content listener is

```
<p>SaVE 1111</p>
<p><br></p>
<p>sAVE 222222</p>
<p><br></p>
<p><br></p>
<p><br></p>
```
I get a console error that may help. 

```
quill.js:4401 Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at Scroll2.update (quill.js:4401:22)
    at MutationObserver.<anonymous> (quill.js:7191:19)
update @ quill.js:4401
(anonymous) @ quill.js:7191
```

**Browser (please complete the following information):**
 - Chrome

Any feedback or assistance is appreciated.

**Comment by nlonidier-sixmo** [comment]
After further review it seems the issue is the the combination of the 

`<div id="divRplyFwdMsg" dir="ltr">` and `<font style="font-size:11pt" face="Calibri, sans-serif" color="#000000">`

tags. When I remove both of the elements the content is returned but just with none of the styling. The `<hr>` element doesn't break things but it is never returned in either instance. Maybe the editor has very specific elements that are allowable? Maybe Microsoft's weird HTML response is just not compatible? 

I'm sure this is intentional but I thought I would leave this issue open just in case the devs want to review or elaborate. 

My coworker is working on a wrapper component and intends to parse the HTML into delta format to suit other purposes. I'm hopeful this will fix the issue but I'm not sure.
